# Modify this GitHub Actions workflow according to your needs, you can also add another workflow file in the same directory.
# Learn more: https://docs.github.com/en/actions/how-tos/use-cases-and-examples/building-and-testing

name: Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check-format:
    name: Check Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v5.0.0

      - name: Check Formatting
        uses: dprint/check@v2.3
