# Add more jobs here or create additional workflow files in this directory.

name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Install dprint
        run: |
          curl -fsSL https://dprint.dev/install.sh | sh
          echo "$HOME/.dprint/bin" >> $GITHUB_PATH

      - name: Install Lefthook
        run: |
          curl -1sLf 'https://dl.cloudsmith.io/public/evilmartians/lefthook/setup.deb.sh' | sudo -E bash
          sudo apt install lefthook

      - name: Check pre-commit hook
        run: lefthook run pre-commit --all-files
